[workspace]
resolver = "3"
members = [
    "crates/lexift-app",
    "crates/lexift-core",
    "crates/lexift-ui",
    "crates/lexift-platform",
    "crates/lexift-translate",
    "crates/lexift-config",
    "crates/lexift-observability",
]
default-members = ["crates/lexift-app"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "GPL-3.0-only"

[workspace.dependencies]
lexift-core = { path = "crates/lexift-core" }
lexift-ui = { path = "crates/lexift-ui" }
lexift-platform = { path = "crates/lexift-platform" }
lexift-translate = { path = "crates/lexift-translate" }
lexift-config = { path = "crates/lexift-config" }
lexift-observability = { path = "crates/lexift-observability" }
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls", "system-proxy"] }
atomic-write-file = "0.3.1"
dirs = "7.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slint = { version = "1.17.1", default-features = false, features = [
    "backend-winit",
    "compat-1-2",
    "renderer-femtovg",
    "std",
] }
slint-build = "1.17.1"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "time"] }
toml = "1.1.6"
windows = "0.62.2"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
