export global AppAssets {
    out property <image> app-icon: @image-url("../../../../assets/app-icons/lexift.png");
    out property <image> icon-pin: @image-url("../assets/icons/pin.svg");
    out property <image> icon-close: @image-url("../assets/icons/close.svg");
    out property <image> icon-copy: @image-url("../assets/icons/copy.svg");
    out property <image> icon-paste: @image-url("../assets/icons/paste.svg");
    out property <image> icon-volume: @image-url("../assets/icons/volume.svg");
    out property <image> icon-translate: @image-url("../assets/icons/translate.svg");
    out property <image> icon-swap-horizontal: @image-url("../assets/icons/swap-horizontal.svg");
    out property <image> icon-expand-more: @image-url("../assets/icons/expand-more.svg");
    out property <image> icon-expand-less: @image-url("../assets/icons/expand-less.svg");
    out property <image> icon-refresh: @image-url("../assets/icons/refresh.svg");
}
