export global Colors {
    in-out property <color> background: #f8f9fa;
    in-out property <color> surface: #ffffff;
    in-out property <color> foreground: #202124;
    in-out property <color> secondary-foreground: #5f6368;
    in-out property <color> outline: #dadce0;
    in-out property <color> primary: #1967d2;
    in-out property <color> primary-container: #e8f0fe;
    in-out property <color> error: #b3261e;
    in-out property <color> success: #137333;
    in-out property <color> icon-button-hover: #20212414;
    in-out property <color> icon-button-pressed: #1967d21f;
    in-out property <color> scrollbar-track-hover: #2021240d;
    in-out property <color> scrollbar-thumb: #5f636845;
    in-out property <color> scrollbar-thumb-hover: #5f636870;
    in-out property <color> scrollbar-thumb-pressed: #5f63688f;
}
