export global Colors {
    in-out property <color> background: #f8f9fa;
    in-out property <color> surface: #ffffff;
    in-out property <color> foreground: #202124;
    in-out property <color> secondary-foreground: #5f6368;
    in-out property <color> outline: #dadce0;
    in-out property <color> primary: #1967d2;
    in-out property <color> primary-container: #e8f0fe;
    in-out property <color> error: #b3261e;
    in-out property <color> icon-button-hover: #20212414;
    in-out property <color> icon-button-pressed: #1967d21f;
}
